version: "3"
services:
  mongo:
    image: mongo
    container_name: product-service-mongo-db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./dbdata:/data/db
  mongo-express:
    image: mongo-express
    container_name: product-service-mongo-express
    restart: always
    ports:
      - 8081:8081