# Uses mysql database with root access
# TODO createDatabaseIfNotExist=true doesn't work. So make sure the database is created
spring:
  r2dbc:
    url: r2dbcs:mysql://${spring.r2dbc.host}:3306/user_service_db
    username: root
    password: password
    host: 127.0.0.1