server:
  port: 8091

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG
    org.springframework.data.couchbase.repository.query: DEBUG

spring:
  application:
    name: product-service
  data:
    mongodb:
      database: productdb
  profiles:
    active: dev
